version: "3.9"
services:
  api:
    build: .
    container_name: prisma-server-api
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    restart: always
    environment:
       DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
       REDIS_HOST: redis
       REDIS_PORT: 6379
       POSTGRES_DB: kapaoil_DB

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kapaoil_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data

volumes:
  postgres-data:
    driver: local
  redisDB:

