version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kapaoil_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - sai

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
    networks:
      - sai

  api:
    build: .
    container_name: prisma-server-api
    links:
      - db
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    restart: always
    environment:
      - WAIT_HOSTS: db:5432, redis:6379
    networks:
      - sai

networks:
  sai:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redisDB:

